### ISSUE TITLE
ОФД и ОИСМ

### ISSUE THREAD

**Issue by legalizedeath** [adslbarxatov/KassArray#1]
Добрый день. Подскажите, как определяются настройки ОФД и ОИСМ для отправки документов и уведомлений о продаже маркированных товаров. Как быть в ситуации, когда ОФД и ОИСМ разные, например когда ОФД это gate.ofd.ru, а ОИСМ k-server.1-ofd.ru?

**Comment by adslbarxatov** [comment]
Доброго времени суток!

Прежде всего, благодарим за освещение экстремальной, но всё же вероятной ситуации.

На данный момент, приложение содержит справочник, сопоставляющий связью «1-1» ИНН ОФД и параметры связи. ИНН ОФД, в свою очередь, извлекается из данных последней (пере) регистрации.

Для разрешения заявленной ситуации можно воспользоваться функцией ручной отправки. Она позволяет выбрать ОФД, игнорируя параметры (пере)регистраций. При этом следует учитывать, что обмен в приложении идёт всегда в следующем порядке:
- обмен ФД;
- обмен УРМТ;
- обновление ключей.

То есть, можно воспользоваться следующим алгоритмом:
- выбрать один ОФД для передачи документов;
- дождаться их отправки;
- дождаться сообщения об ошибке отправки уведомлений о реализации МТ;
- выбрать другой ОФД для УРМТ;
- поскольку документы ОФД уже отправлены, шаг будет пропущен, и начнётся отправка УРМТ;
- дождаться отправки уведомлений и обновления ключей.

---

Просим уточнить, достаточно ли будет такого варианта, или реализация изолированной отправки разным ОФД всё-таки необходима?

**Comment by legalizedeath** [comment]
Спасибо за оперативный ответ. Думаю такого варианта решения проблемы вполне достаточно, как вы правильно заметили эта ситуация довольно редко встречается. Отдельное спасибо за сам софт, все просто и понятно, а главное обновляется:)

**Comment by adslbarxatov** [comment]
Спасибо Вам за активное участие в жизни проекта! Рады, что продукт оказался полезным.

---

Если у Вас возникнут дополнительные вопросы или пожелания, пожалуйста, инициируйте новую проблему в данном репозитории
